"""Rebuild browser-safe reference snapshots from the authorised Cleaned_Dataset.

Usage: python3 backend/scripts/import-cp3-reference-data.py [local-data-directory]
The input CSV files stay local in docs; only validated reference snapshots ship.
No external notebook or downloaded executable is run.
"""
import csv
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DATA = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / 'docs/cp3-data'
SRC = ROOT / 'backend/src'
manifest = {}


def read(relative):
    path = DATA / relative
    raw = path.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    hashes = path.parent / 'outputs_sha256.csv'
    verified = False
    if hashes.exists():
        expected = next((r for r in csv.DictReader(hashes.open(encoding='utf-8-sig')) if r['file'] == path.name), None)
        if expected:
            assert expected['sha256'] == digest and int(expected['bytes']) == len(raw), relative
            verified = True
    rows = list(csv.DictReader(raw.decode('utf-8-sig').splitlines()))
    manifest[relative] = dict(sha256=digest, rows=len(rows), sourceManifestVerified=verified)
    return rows, 'Cleaned_Dataset/' + relative + '; SHA-256 ' + digest


def write(relative, text):
    (SRC / relative).write_text('// Generated by backend/scripts/import-cp3-reference-data.py. Do not edit by hand.\n' + text, encoding='utf-8')


def js(value):
    return json.dumps(value, ensure_ascii=True, separators=(',', ':'))


def number(value):
    return float(value) if value.strip() else None


categories, provenance = read('00_category_mappings/category_map.csv')
assert len(categories) == 80 and len({r['category'] for r in categories}) == 80
dictionary = [dict(category=r['category'], keywords=r['keywords'].split('|') if r['keywords'] else [],
                   isFood=r['is_food'].lower() in ('true', '1'), provenance=provenance) for r in categories]
write('reference-data/cp3-category-dictionary.ts',
      'export const CP3_CATEGORY_DICTIONARY = ' + js(dictionary) + ' as const;\n')

products, provenance = read('03_storage_window/foodkeeper_products_cleaned.csv')
aggregates, aggregate_source = read('03_storage_window/storage_window_by_category.csv')
modes = dict(fridge='refrigerate', freezer='freeze', pantry='pantry')
picks = []
for r in products:
    low, high = number(r['min_days']), number(r['max_days'])
    assert low and high and 0 < low <= high
    picks.append(dict(id='fk128-' + r['product_id'] + '-' + r['storage'],
                      name=' / '.join(v for v in [r['product'], r['subtitle'], r['window_type']] if v),
                      categoryId=int(r['category_id']), categoryName=r['category'],
                      windows={modes[r['storage']]: dict(minDays=low, maxDays=high)},
                      version='128', provenance=provenance, windowType=r['window_type']))
assert len(picks) == 994 and len({r['id'] for r in picks}) == 994
groups = [dict(categoryId=int(r['category_id']), name=r['category'], storage=modes[r['storage']],
               p25MinimumDays=number(r['p25_min_days']), productCount=int(r['n_products']))
          for r in aggregates if r['storage'] != 'pantry']
write('reference-storage-data.ts',
      'export const FOODKEEPER_REFERENCE_SOURCE = ' + js(aggregate_source) + ';\n'
      + 'export const FOODKEEPER_PRODUCTS = ' + js(picks) + ' as const;\n'
      + 'export const FOODKEEPER_AGGREGATES = ' + js(groups) + ' as const;\n')

factors, provenance = read('05_co2e_factors/co2e_factors.csv')
old = (SRC / 'reference-carbon-data.ts').read_text(encoding='utf-8')
metadata_start = old.index('export type CarbonSourceId')
metadata_end = old.index('export interface CarbonReferenceRow')
metadata = old[metadata_start:metadata_end]
rows = [dict(category=r['category'], inCategoryTable=r['in_category_table'].lower() == 'true',
             sources={s: number(r[s]) for s in ['SEL', 'AGB', 'Poore', 'BCD'] if r[s].strip()},
             bounded=dict(status=r['status'], value=number(r['factor']), low=number(r['range_low']), high=number(r['range_high']))) for r in factors]
assert len(rows) == 90 and len({r['category'] for r in rows}) == 90
assert all(v > 0 for r in rows for v in r['sources'].values())
write('reference-carbon-data.ts',
      'export const CARBON_REFERENCE_VERSION = "stockless-cp3-v2-cleaned-2026-10-07";\n'
      + 'export const CARBON_REFERENCE_PROVENANCE = ' + js(provenance) + ';\n' + metadata
      + 'export interface CarbonReferenceRow { readonly category: string; readonly inCategoryTable: boolean; readonly sources: Readonly<Partial<Record<CarbonSourceId,number>>>; readonly bounded: { readonly status: string; readonly value: number | null; readonly low: number | null; readonly high: number | null }; }\n'
      + 'export const CARBON_REFERENCE_ROWS: readonly CarbonReferenceRow[] = Object.freeze(' + js(rows)
      + '.map(row => Object.freeze({...row,sources:Object.freeze(row.sources),bounded:Object.freeze(row.bounded)})) as CarbonReferenceRow[]);\n')

prices, provenance = read('04_reference_price/price_reference.csv')
items, item_source = read('00_category_mappings/pricecatcher_items_by_category.csv')
fk, fk_source = read('00_category_mappings/pricecatcher_category_to_foodkeeper.csv')
item_map = {r['item_code']: r for r in items}
fk_map = {r['item_category']: r for r in fk}
references = []
for r in prices:
    item = item_map.get(r['item_code'], {})
    storage = fk_map.get(r['item_category'], {})
    references.append(dict(itemCode=r['item_code'], name=r['item'], unit=r['unit'],
                           priceMYR=number(r['ref_price_rm']), category=item.get('category', ''),
                           foodKeeperCategoryId=int(storage['foodkeeper_category_id']) if storage.get('foodkeeper_category_id') else None,
                           basis=r['basis'], sampleCount=int(r['n_prices']), maxMonthDrift=number(r['max_month_drift']),
                           provenance=provenance, mappingProvenance=item_source + '; ' + fk_source))
assert len(references) == 328 and len({r['itemCode'] for r in references}) == 328
write('reference-data/cp3-prices.ts', 'export const PRICECATCHER_REFERENCES = ' + js(references) + ' as const;\n')
densities, provenance = read('02_density/density.csv')
write('reference-data/cp3-density.ts', 'export const CP3_DENSITY_REFERENCE = ' + js([
    dict(category=r['category'], faoEntry=r['fao_entry'], kgPerLitre=number(r['density_g_per_ml']), provenance=provenance) for r in densities]) + ' as const;\n')
write('reference-data/cp3-source-manifest.ts', 'export const CP3_SOURCE_MANIFEST = ' + js(manifest) + ' as const;\n')
print(json.dumps(manifest, indent=2))
