import type {
  CanonicalField,
  FieldDefinition,
} from "./contracts.ts";

export const FIELD_REGISTRY: Readonly<Record<CanonicalField, FieldDefinition>> = {
  transaction_date: {
    field: "transaction_date",
    label: "Sale date",
    description: "When did each sale or return happen?",
    status: "core",
    valueKind: "date",
    grain: "transaction",
    unlocks: ["Weekly product history", "Timeline gap evidence", "Recent weekly average", "Descriptive weeks of cover"],
    aliases: ["transaction date", "sale date", "sales date", "transaction datetime", "txn date", "txndate", "sold at", "tarikh jualan"],
    acquisitionSource: "file",
  },
  product_code: {
    field: "product_code",
    label: "Product code, SKU or barcode",
    description: "A code that is unique to each product, so two products are never mixed up.",
    status: "conditional_core",
    valueKind: "text",
    grain: "product",
    unlocks: ["Weekly product history", "Timeline gap evidence", "Recent weekly average", "Stock freshness", "Descriptive weeks of cover", "Purchase audit", "Expiry-aware note", "Supplier scenario"],
    aliases: ["product code", "sku", "barcode", "item code", "stock code", "product id", "plu", "kod produk"],
    acquisitionSource: "file",
  },
  product_name: {
    field: "product_name",
    label: "Product name",
    description: "The name you use for the product.",
    status: "conditional_core",
    valueKind: "text",
    grain: "product",
    unlocks: ["Weekly product history", "Timeline gap evidence", "Recent weekly average", "Stock freshness", "Descriptive weeks of cover", "Purchase audit", "Expiry-aware note", "Supplier scenario"],
    aliases: ["product name", "item name", "product", "item", "description", "nama produk"],
    acquisitionSource: "file",
  },
  pack_variant: {
    field: "pack_variant",
    label: "Pack size",
    description: "The pack size, so a 10-pack is never counted as the same thing as a 20-pack.",
    status: "conditional_core",
    valueKind: "text",
    grain: "product",
    unlocks: ["Weekly product history", "Timeline gap evidence", "Recent weekly average", "Stock freshness", "Descriptive weeks of cover", "Purchase audit", "Expiry-aware note", "Supplier scenario"],
    aliases: ["pack variant", "variant", "unit", "uom", "size", "pack", "unit size"],
    acquisitionSource: "file",
  },
  quantity_sold: {
    field: "quantity_sold",
    label: "Quantity sold",
    description: "How many units were sold or returned.",
    status: "core",
    valueKind: "decimal",
    grain: "transaction",
    unlocks: ["Weekly product history", "Timeline gap evidence", "Recent weekly average", "Descriptive weeks of cover"],
    aliases: ["quantity sold", "qty sold", "units sold", "sold quantity", "sales qty", "quantity", "qty", "pieces sold", "kuantiti jualan"],
    acquisitionSource: "file",
  },
  current_stock: {
    field: "current_stock",
    label: "Stock on hand",
    description: "How much you have on the shelf right now.",
    status: "feature_dependent",
    valueKind: "non_negative_decimal",
    grain: "product",
    unlocks: ["Stock freshness", "Descriptive weeks of cover", "Purchase audit"],
    aliases: ["current stock", "stock on hand", "soh", "closing stock", "current inventory", "inventory qty", "remaining units", "baki stok"],
    acquisitionSource: "either",
  },
  stock_as_of_date: {
    field: "stock_as_of_date",
    label: "Stock count date",
    description: "When was your current stock counted?",
    status: "feature_dependent",
    valueKind: "date",
    grain: "product",
    unlocks: ["Stock freshness", "Descriptive weeks of cover", "Purchase audit"],
    aliases: ["stock as of date", "stock date", "snapshot date", "inventory date", "count date", "stock count date", "stock take day", "inventory as at", "inventoryasat", "tarikh stok"],
    acquisitionSource: "either",
  },
  planned_order_quantity: {
    field: "planned_order_quantity",
    label: "Planned orders",
    description: "An order you have already planned but not yet placed.",
    status: "feature_dependent",
    valueKind: "non_negative_integer",
    grain: "order",
    unlocks: ["Purchase audit"],
    aliases: ["planned order quantity", "planned order", "order qty", "purchase quantity"],
    acquisitionSource: "either",
  },
  incoming_stock_quantity: {
    field: "incoming_stock_quantity",
    label: "Incoming stock",
    description: "Stock you have ordered that has not arrived yet.",
    status: "feature_dependent",
    valueKind: "non_negative_integer",
    grain: "inbound",
    unlocks: ["Purchase audit"],
    aliases: ["incoming stock quantity", "incoming quantity", "on order", "inbound qty"],
    acquisitionSource: "either",
  },
  incoming_stock_expected_date: {
    field: "incoming_stock_expected_date",
    label: "Incoming stock date",
    description: "The expected arrival date of incoming stock.",
    status: "later_locked",
    valueKind: "date",
    grain: "inbound",
    unlocks: ["Purchase audit"],
    aliases: ["incoming stock expected date", "expected arrival date", "eta", "delivery date"],
    acquisitionSource: "either",
  },
  expiry_date: {
    field: "expiry_date",
    label: "Expiry date",
    description: "When a batch of the product expires.",
    status: "feature_dependent",
    valueKind: "date",
    grain: "lot",
    unlocks: ["Expiry-aware note"],
    aliases: ["expiry date", "expiration date", "best before", "use by"],
    acquisitionSource: "either",
  },
  expiry_quantity: {
    field: "expiry_quantity",
    label: "Expiry quantity",
    description: "The quantity affected by a product-lot expiry date.",
    status: "later_locked",
    valueKind: "non_negative_decimal",
    grain: "lot",
    unlocks: ["Expiry-aware note"],
    aliases: ["expiry quantity", "expiring quantity", "expiry qty"],
    acquisitionSource: "either",
  },
  supplier_id_or_name: {
    field: "supplier_id_or_name",
    label: "Supplier details",
    description: "The supplier responsible for the product.",
    status: "later_locked",
    valueKind: "text",
    grain: "supplier",
    unlocks: ["Supplier scenario"],
    aliases: ["supplier", "supplier id", "supplier name", "vendor", "vendor id"],
    acquisitionSource: "either",
  },
  supplier_lead_time_days: {
    field: "supplier_lead_time_days",
    label: "Supplier lead time in days",
    description: "The number of days a supplier usually needs to deliver.",
    status: "later_locked",
    valueKind: "non_negative_integer",
    grain: "supplier",
    unlocks: ["Supplier scenario"],
    aliases: ["supplier lead time days", "lead time days", "lead time"],
    acquisitionSource: "either",
  },
  pack_size: {
    field: "pack_size",
    label: "Pack size",
    description: "A numeric or well-defined pack size used for later pack rounding.",
    status: "later_locked",
    valueKind: "text",
    grain: "product",
    unlocks: ["Supplier scenario"],
    aliases: ["pack size", "case size", "carton size", "units per pack"],
    acquisitionSource: "either",
  },
};

export const CANONICAL_FIELDS = Object.freeze(Object.keys(FIELD_REGISTRY) as CanonicalField[]);

export const CORE_COLUMN_PATHS = Object.freeze([
  {
    id: "stable" as const,
    label: "One code column",
    hint: "SKU, barcode or product code",
    detail: "Use a SKU, barcode, or product code to identify each product.",
    requiredFields: ["transaction_date", "product_code", "quantity_sold"] as const,
  },
  {
    id: "composite" as const,
    label: "Product name + pack size",
    hint: "Product name + pack size",
    detail: "Use the product name together with its pack size.",
    requiredFields: ["transaction_date", "product_name", "pack_variant", "quantity_sold"] as const,
  },
]);

export const UPLOAD_REQUIREMENTS = Object.freeze({
  maxBytes: 10 * 1024 * 1024,
  maxRows: 100_000,
  supportedExtension: ".csv",
  supportedDelimiters: [",", ";", "\t"] as const,
  coreDescription:
    "Required data is enough to get started. Optional data unlocks deeper insights.",
});

export const PRIVACY_NOTICE = Object.freeze({
  beforeUpload:
    "Your raw CSV rows are processed in this browser and no account is required. StockLess may save column headings and confirmed matching rules in this browser, but your preview values, rows, derived series, and product identifiers are not uploaded to an AI or API service.",
  persistence:
    "Only saved column matching remains for returning use. Dataset rows, forecasts and purchase plans stay in the active session and are not saved in the browser database.",
});
