import { useEffect, useMemo, useState, type KeyboardEvent } from 'react';
import { getLocale, useLanguage } from '../i18n/index.ts';
import { buildEnvironmentalImpact, buildImpactReview, buildMissingCostQueue, buildAnalysisReport, CARBON_MALAYSIA_ILLUSTRATION, evaluateProductPurchasePlan,
  type CarbonImpactResult, type CarbonImpactSummary, type DemandForecastReview, type MonetaryTotal, type PlanningContexts, type ProductPlanningContext, type ReadinessSnapshot, type SupplierOrderTerms } from '../engine.ts';
import { evaluatePurchaseProduct, joinPurchaseEvidence, type PurchaseDrafts } from '../purchase-plan/model.ts';
import { getSavedDataset, savedPurchaseDecisions, savedStockOutcomes, type SavedDataset } from '../storage/saved-datasets.ts';
import { downloadAnalysisWorkbook, downloadFinalisedOrdersWorkbook, printAnalysisReport } from '../purchase-plan/analysis-report-export.ts';
import { PlanningInputsPanel } from '../components/PlanningInputsPanel.tsx';
import { OutcomePeriodComparison } from '../components/OutcomePeriodComparison.tsx';
import { DecisionOutcomeControls } from '../components/DecisionOutcomeControls.tsx';
import './impact-reference.css';
import '../components/cp3-controls.css';

interface Props {
  snapshot: ReadinessSnapshot; forecast: DemandForecastReview; drafts: PurchaseDrafts;
  contexts?: PlanningContexts; datasetId?: string; shopName?: string; datasetName?: string;
  supplierDrafts?: Readonly<Record<string, SupplierOrderTerms | undefined>>;
  onContextChange?: (key:string,value:ProductPlanningContext)=>void;
  onBack:()=>void; onNew?:()=>void;
}
const EMPTY_CONTEXTS: PlanningContexts = Object.freeze({});

/** Compatibility helper; business calculations are owned by the shared engine. */
export function calculatePotentialExcess(snapshot: ReadinessSnapshot, forecast: DemandForecastReview, drafts: PurchaseDrafts) {
  return buildImpactReview(snapshot,forecast,drafts).products.flatMap(p => p.excessUnits === undefined ? [] : [{key:p.productKey,name:p.name,sku:p.code,available:p.available!,demandHigh:p.demandHigh!,units:p.excessUnits}]);
}

export function ImpactDashboard({snapshot,forecast,drafts,contexts=EMPTY_CONTEXTS,datasetId,shopName,datasetName,supplierDrafts,onContextChange,onBack,onNew}:Props) {
  const language=useLanguage(), c=(en:string,zh:string,ms:string)=>language==='zh'?zh:language==='ms'?ms:en;
  const n=(v:number)=>v.toLocaleString(getLocale(),{maximumFractionDigits:3});
  const unavailable=c('Unavailable','不可用','Tidak tersedia');
  const products=useMemo(()=>joinPurchaseEvidence(snapshot,forecast,contexts),[snapshot,forecast,contexts]);
  const plans=useMemo(()=>products.flatMap(p=>{const plan=evaluatePurchaseProduct(p,snapshot.analysisDate,drafts[p.key]??p.fileInputs,evaluateProductPurchasePlan,p.fileExpiry); return plan?[plan]:[];}),[products,snapshot.analysisDate,drafts]);
  const impact=useMemo(()=>buildImpactReview(snapshot,forecast,drafts,undefined,contexts),[snapshot,forecast,drafts,contexts]);
  const costQueue=useMemo(()=>buildMissingCostQueue(snapshot,impact,contexts),[snapshot,impact,contexts]);
  const [saved,setSaved]=useState<SavedDataset>();
  const [revision,setRevision]=useState(0), [error,setError]=useState(''), [busy,setBusy]=useState(false);
  const [lens,setLens]=useState<'business'|'environment'>('business');
  const [selected,setSelected]=useState(products[0]?.key??'');
  useEffect(()=>{if(!products.some(p=>p.key===selected))setSelected(products[0]?.key??'');},[products,selected]);
  useEffect(()=>{let cancelled=false;setSaved(undefined); if(datasetId)void getSavedDataset(datasetId).then(value=>{if(!cancelled)setSaved(value);}).catch(()=>{if(!cancelled)setError(c('Saved history could not be read.','无法读取已保存记录。','Sejarah tersimpan tidak dapat dibaca.'));});return()=>{cancelled=true;};},[datasetId,revision]);
  const outcomes=useMemo(()=>saved?savedStockOutcomes(saved):[],[saved]);
  const environmental=useMemo(()=>buildEnvironmentalImpact(snapshot,impact,contexts,outcomes,{datasetId}),[snapshot,impact,contexts,outcomes,datasetId]);
  const monetary=(total:MonetaryTotal)=>total.state==='estimated'?`MYR ${total.amount.toFixed(2)}`:unavailable;
  const carbon=(summary:CarbonImpactSummary)=>summary.state==='estimated'?`≈ ${n(summary.kgCO2e!)} kg CO₂e`:summary.state==='no_records'?c('No outcome recorded','尚无实际结果记录','Tiada hasil direkodkan'):unavailable;
  const excess=impact.products.reduce((sum,p)=>sum+(p.excessUnits??0),0);
  const selectedProduct=products.find(p=>p.key===selected), selectedPlan=plans.find(p=>p.productKey===selected);
  const refresh=()=>setRevision(value=>value+1);
  const switchTab=(event:KeyboardEvent<HTMLButtonElement>)=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?'business':event.key==='End'?'environment':lens==='business'?'environment':'business';setLens(next);document.getElementById(`${next}-tab`)?.focus();};
  const makeReport=()=>buildAnalysisReport({snapshot,forecast,plans,impact,datasetId:datasetId??'sample-preview',shopName,datasetName,
    decisions:saved?savedPurchaseDecisions(saved):[],outcomes,carbonResults:[...environmental.actualResults,...environmental.potentialResults,...environmental.scenarioResults],
    supplierScenariosByProduct:Object.fromEntries(Object.entries(supplierDrafts??{}).filter((entry):entry is [string,SupplierOrderTerms]=>!!entry[1]).map(([key,terms])=>[key,[{id:'current-terms',name:c('Entered supplier terms','已填写的供应商条件','Terma pembekal dimasukkan'),terms}]]))});
  const download=async(finalOnly=false)=>{setError('');setBusy(true);try{const report=makeReport();if(finalOnly)await downloadFinalisedOrdersWorkbook(report);else await downloadAnalysisWorkbook(report);}catch(e){setError(e instanceof Error?e.message:unavailable);}finally{setBusy(false);}};
  const pdf=async()=>{setError('');setBusy(true);try{const {downloadAnalysisPdf}=await import('../purchase-plan/analysis-report-pdf.ts');await downloadAnalysisPdf(makeReport());}catch(e){setError(e instanceof Error?e.message:unavailable);}finally{setBusy(false);}};
  const explain=(result:CarbonImpactResult,index:number)=><details className="cp3-controls" key={`${result.kind}-${result.productKey}-${index}`}><summary>{result.productName??result.productKey} · {result.state==='estimated'?`${n(result.kgCO2e)} kg CO₂e`:result.state==='no_record'?c('No outcome recorded','尚无实际结果记录','Tiada hasil direkodkan'):unavailable}</summary>
    {result.state==='estimated'?<><p>{result.factor.label==='sources_agree'?c('Sources agree','来源一致','Sumber bersetuju'):c('Estimate; sources disagree, bounded within ×2','估算；来源不一致，但均在 ×2 内','Anggaran; sumber berbeza, dalam julat ×2')}</p><p>{n(result.quantity??0)} {result.quantityUnit} → {n(result.massKg)} kg · {c('Mass basis','重量依据','Asas jisim')}: {c(result.massBasis, result.massBasis==='measured'?'实测':result.massBasis==='estimated'?'估算换算':'已知重量换算',result.massBasis==='measured'?'diukur':result.massBasis==='estimated'?'penukaran anggaran':'penukaran diketahui')}</p>{result.baseline&&<p>{c('Baseline','比较基线','Garis dasar')}: {result.baseline}</p>}<p>{result.calculation}</p><p>{result.conversionSource}</p><p>{c('Source range','全部来源范围','Julat semua sumber')}: {n(result.factor.sourceRange!.low)}–{n(result.factor.sourceRange!.high)} kg CO₂e/kg · {c('Calculated range','计算范围','Julat pengiraan')}: {n(result.kgCO2eRange.low)}–{n(result.kgCO2eRange.high)} kg CO₂e</p><ul>{result.factor.sources.map(s=><li key={s.id}>{s.name} ({result.factor.selectedSources.includes(s.id)?c('used in factor','计入因子','digunakan dalam faktor'):c('shown for range only','仅用于来源范围','julat sumber sahaja')}): {n(s.value)} kg CO₂e/kg · {s.version} · {s.boundary}</li>)}</ul><p>{result.factor.explanation} {result.limitation}</p></>:<p>{result.reason} {result.correctiveAction}</p>}
  </details>;
  const summaryCard=(title:string,summary:CarbonImpactSummary)=><div><span>{title}</span><b>{carbon(summary)}</b><small>{c('Contributing products','计入商品','Produk menyumbang')}: {summary.includedProductCount}/{summary.totalProductCount}</small>{summary.massKg!==undefined&&<p>{n(summary.massKg)} kg · {c('Source-agreement mass / estimated-factor mass','来源一致重量／估算因子重量','Jisim sumber bersetuju / faktor anggaran')}: {n(summary.massKgSourcesAgree)} / {n(summary.massKgEstimate)} kg</p>}</div>;
  return <main className="impact" aria-labelledby="impact-title">
    <div className="sx-head"><div><p className="eyebrow">StockLess · {snapshot.sourceMode==='sample'?c('Sample data','示例数据','Data contoh'):c('Your dataset','您的数据集','Set data anda')}</p><h1 id="impact-title" className="impact__title">{c('See the impact of your purchase plan','查看采购计划的影响','Lihat impak pelan belian anda')}</h1><p>{shopName||c('Shop not named','未命名店铺','Kedai belum dinamakan')} · {datasetName||snapshot.sourceName} · {snapshot.analysisDate}</p><p>{c('Current plan and restock scenario are estimates. Recorded sales and waste are shown separately.','当前计划和补货情景均为估算；实际销售和报损记录单独展示。','Pelan semasa dan senario stok semula ialah anggaran. Jualan dan pembaziran sebenar ditunjukkan berasingan.')}</p></div></div>
    <div className="cp3-actions"><button type="button" className="btn btn--ghost" onClick={onBack}>{c('← Back to purchase plan','← 返回采购计划','← Kembali ke pelan belian')}</button><button type="button" className="btn btn--ghost" disabled={busy} onClick={()=>void download()}>{c('Download analysis Excel','下载分析 Excel','Muat turun Excel analisis')}</button><button type="button" className="btn btn--ghost" disabled={busy} onClick={()=>void download(true)}>{c('Download final orders Excel','下载最终订单 Excel','Muat turun Excel pesanan akhir')}</button><button type="button" className="btn btn--ghost" disabled={busy} onClick={()=>void pdf()}>{c("Download analysis PDF","下载分析 PDF","Muat turun PDF analisis")}</button><button type="button" className="btn btn--ghost" onClick={()=>{try{printAnalysisReport(makeReport());}catch(e){setError(e instanceof Error?e.message:unavailable);}}}>{c('Print / Save PDF','打印／保存 PDF','Cetak / Simpan PDF')}</button></div>
    {error&&<p role="alert">{error}</p>}
    <div className="sx-tabs" role="tablist" aria-label={c('Impact view','影响视图','Paparan impak')}><button type="button" role="tab" id="business-tab" aria-controls="business-impact" aria-selected={lens==='business'} tabIndex={lens==='business'?0:-1} onKeyDown={switchTab} onClick={()=>setLens('business')}>{c('Business','经营','Perniagaan')}</button><button type="button" role="tab" id="environment-tab" aria-controls="environment-impact" aria-selected={lens==='environment'} tabIndex={lens==='environment'?0:-1} onKeyDown={switchTab} onClick={()=>setLens('environment')}>{c('Environmental','环境','Alam sekitar')}</button></div>
    <section id="business-impact" role="tabpanel" aria-labelledby="business-tab" hidden={lens!=='business'}>
      <div className="cp3-impact-totals">{([[c('Planned purchase spend','计划采购支出','Perbelanjaan belian dirancang'),impact.totals.plannedSpend],[c('Excess-stock cost','过量库存成本','Kos stok berlebihan'),impact.totals.excessCost],[c('Restock scenario spend','补货情景支出','Belanja senario stok semula'),impact.totals.scenarioSpend],[c('Estimated purchase-spend difference','预计采购支出差异','Perbezaan belanja belian dianggarkan'),impact.totals.spendDifference]] as const).map(([title,total])=><div key={title}><span>{title}</span><b>{monetary(total)}</b><small>{c('Included / total','计入／总商品','Termasuk / jumlah')}: {total.includedCount}/{impact.products.length}</small></div>)}</div>
      <p>{c('Difference = current planned spend − restock-scenario spend, for the same eligible products. It is not achieved savings, profit or selling-price revenue.','差异＝当前计划支出－补货情景支出，两者使用相同的可计入商品；它不是已实现节省、利润或销售额。','Perbezaan = belanja dirancang semasa − belanja senario stok semula bagi produk layak sama. Ia bukan penjimatan, keuntungan atau hasil jualan sebenar.')}</p>
      <p>{c('Current planned spend for comparable products','参与情景比较的当前采购支出','Belanja dirancang semasa bagi produk boleh dibandingkan')}: {monetary(impact.totals.comparisonPlannedSpend)} · {impact.totals.comparisonPlannedSpend.includedCount}/{impact.products.length}. {c('Compare this subtotal with the restock scenario above. Other costed orders remain in total planned spend.','此小计与上方补货情景比较；其他已有成本的订单仍计入总计划支出。','Bandingkan jumlah kecil ini dengan senario stok semula di atas. Pesanan lain dengan kos kekal dalam jumlah belanja dirancang.')}</p>
      <p>{c('Potential excess','潜在过量库存','Lebihan berpotensi')}: {impact.assessedCount?n(excess):unavailable} {c('sales units','销售单位','unit jualan')} · {impact.assessedCount}/{impact.products.length} {c('assessed','已评估','dinilai')}</p>
      <details className="cp3-controls"><summary>{c('Missing purchase costs: first 10 priorities','缺失采购成本：优先补录前 10 项','Kos belian tiada: 10 keutamaan pertama')}</summary><p>{c('Ranked by potential excess × explicitly matched reference retail price. This reference amount is not an estimated purchase cost. Unmatched items remain listed for manual input.','按潜在过量 × 人工确认对应的参考零售价排序。此参考金额不是采购成本估算。未匹配的商品仍列出供人工补录。','Disusun mengikut lebihan berpotensi × harga runcit rujukan dipadankan secara nyata. Amaun rujukan ini bukan kos belian. Item tanpa padanan kekal untuk input manual.')}</p>{costQueue.top10.map((r,i)=><p key={r.productKey}><button type="button" className="btn btn--ghost" onClick={()=>setSelected(r.productKey)}>{i+1}. {impact.products.find(p=>p.productKey===r.productKey)?.name} · MYR {r.referenceRisk.toFixed(2)}</button><small>{r.source}</small></p>)}{costQueue.remaining.length>0&&<p>{costQueue.remaining.length} {c("more ranked products; the next priorities appear as costs are completed.","个后续排序商品；补录成本后自动显示下一批。","produk berkeutamaan lagi; muncul selepas kos dilengkapkan.")}</p>}{costQueue.unranked.map(r=><p key={r.productKey}><button type="button" className="btn btn--ghost" onClick={()=>setSelected(r.productKey)}>{impact.products.find(p=>p.productKey===r.productKey)?.name} · {c('Unranked: confirm reference or enter purchase cost','未排序：确认参考商品或补录采购成本','Tidak disusun: sahkan rujukan atau masukkan kos belian')}</button></p>)}{!costQueue.top10.length&&!costQueue.unranked.length&&<p>{c('No missing costs for entered orders.','已填写订单均有采购成本。','Tiada kos hilang bagi pesanan dimasukkan.')}</p>}</details>
      <div className="cp3-table"><table><thead><tr>{[c('Product / code / pack','商品／编码／包装','Produk / kod / bungkusan'),c('Planned spend','计划支出','Belanja dirancang'),c('Excess cost','过量成本','Kos lebihan'),c('Difference','差异','Perbezaan'),c('Reason','原因','Sebab')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{impact.products.map(p=><tr key={p.productKey}><td>{p.name}<br />{p.code} · {p.pack}</td>{[p.plannedSpend,p.excessCost,p.spendDifference].map((f,i)=><td key={i}>{f.state==='estimated'?`MYR ${f.amount.toFixed(2)}`:unavailable}</td>)}<td>{p.exclusionReason??(p.excessCost.state!=='estimated'?p.excessCost.reason:p.spendDifference.state!=='estimated'?p.spendDifference.reason:c('Included','已计入','Termasuk'))}</td></tr>)}</tbody></table></div>
    </section>
    <section id="environment-impact" role="tabpanel" aria-labelledby="environment-tab" hidden={lens!=='environment'}>
      <div className="cp3-impact-totals">{summaryCard(c('Recorded waste: estimated CO₂e','实际报损：CO₂e 估算','Pembaziran direkod: anggaran CO₂e'),environmental.recorded)}{summaryCard(c('Potential excess: estimated CO₂e','潜在过量：CO₂e 估算','Lebihan berpotensi: anggaran CO₂e'),environmental.potential)}{summaryCard(c('Named scenario difference','当前计划与补货情景差异','Perbezaan senario dinamakan'),environmental.scenario)}</div>
      <p>{c('CP3 v2: agreeing-group mean; otherwise median only within ×2 of every source, labelled estimate. Single-source factors are excluded. No consumer stage. Confirm every category.','CP3 v2：一致来源组取均值；否则，仅当中位数与每个来源均在 ×2 内时显示估算。单一来源不显示。排除消费者阶段，每个类别均需人工确认。','CP3 v2: min kumpulan sumber bersetuju; jika tidak, median hanya apabila dalam ×2 setiap sumber, berlabel anggaran. Faktor satu sumber dan peringkat pengguna dikecualikan. Sahkan setiap kategori.')}</p>
      <p>{c('The scenario compares potential excess under your current order with the restock recommendation. Positive means potentially less excess; negative means more. It is not a measured reduction.','情景比较当前采购与补货建议下的潜在过量。正值表示可能减少，负值表示可能增加，不代表实测减排。','Senario membandingkan lebihan berpotensi pesanan semasa dengan cadangan stok semula. Positif mungkin kurang; negatif lebih. Ia bukan pengurangan diukur.')}</p>
      <details className="cp3-controls"><summary>{c('Categories to confirm, largest known kg at risk first','待确认类别，按已知风险公斤数排序','Kategori untuk disahkan, kg risiko diketahui terbesar dahulu')}</summary>{environmental.potential.confirmationQueue.length?<ul>{environmental.potential.confirmationQueue.map(r=><li key={r.productKey}><button type="button" className="btn btn--ghost" onClick={()=>setSelected(r.productKey)}>{r.productName??r.productKey} · {r.kgAtRisk===undefined?unavailable:`${n(r.kgAtRisk)} kg`}</button></li>)}</ul>:<p>{c('No pending category confirmations.','没有待确认类别。','Tiada kategori menunggu pengesahan.')}</p>}</details>
      <p>{c('Recorded-waste period: all saved outcome dates for this dataset. Forecast period: the next 28 days from the analysis date. Select equal-length history periods below for a before/after comparison.','实际报损期间：本数据集所有已保存的发生日期。预测期间：分析日起未来 28 天。前后期间比较请使用下方等长日期筛选。','Tempoh sisa direkod: semua tarikh hasil tersimpan set data ini. Tempoh ramalan: 28 hari selepas tarikh analisis. Pilih tempoh sejarah sama panjang di bawah untuk perbandingan sebelum/selepas.')}</p><h2>{c('Why these estimates?','这些估算如何得出？','Mengapa anggaran ini?')}</h2>{environmental.potentialResults.map(explain)}<details className="cp3-controls"><summary>{c('Scenario difference breakdown','情景差异计算明细','Pecahan perbezaan senario')}</summary>{environmental.scenarioResults.map(explain)}</details>
      <details className="cp3-controls"><summary>{c('Recorded waste breakdown','实际报损明细','Pecahan pembaziran direkodkan')}</summary>{outcomes.filter(o=>['discarded','expired'].includes(o.kind)).map(o=><p key={o.id}>{o.date} · {o.productKey} · {o.quantity} {o.unit} · {o.kind}</p>)}{environmental.actualResults.map(explain)}</details>
      <p>{c('Illustrative comparison only','仅作直观比较','Perbandingan ilustrasi sahaja')}: {environmental.potential.kgCO2e===undefined?unavailable:`${n(environmental.potential.kgCO2e/CARBON_MALAYSIA_ILLUSTRATION.kgCO2ePerPersonPerDay)} ${c('Malaysia person-days','马来西亚人均排放天数','hari-orang Malaysia')}`} · 29.95 kg CO₂e/{c('person/day','人／天','orang/hari')} · {CARBON_MALAYSIA_ILLUSTRATION.source}. {c('All sectors; not a food-waste reduction baseline.','包括所有行业，不是食品浪费减排基线。','Semua sektor; bukan garis dasar pengurangan pembaziran makanan.')}</p>
    </section>
    <section className="cp3-controls"><h2>{c('Review a product and record your decision','核对商品并记录决策','Semak produk dan rekod keputusan')}</h2><label>{c('Product','商品','Produk')} <select value={selected} onChange={e=>setSelected(e.target.value)}>{products.map(p=><option key={p.key} value={p.key}>{p.title} · {p.sku} · {p.pack}</option>)}</select></label>
      {selectedProduct&&onContextChange&&<PlanningInputsPanel key={`${snapshot.id}-${selected}`} snapshot={snapshot} productKey={selected} value={contexts[selected]} onChange={value=>onContextChange(selected,value)} />}
      {selectedProduct&&<DecisionOutcomeControls key={`decision-${selected}`} datasetId={datasetId} product={selectedProduct} snapshot={snapshot} plan={selectedPlan} onChanged={refresh} />}
    </section>
    <OutcomePeriodComparison key={`${datasetId}-${revision}`} datasetId={datasetId} currentSnapshot={snapshot} />
    <section className="cp3-controls"><h2>{c('Understanding your impact','了解影响数据','Memahami impak anda')}</h2><p>{c('Food wasted, potential excess and scenario differences are distinct measures. Missing cost, weight, category or outcome remains unavailable; a recorded zero is shown as zero.','实际食物报损、潜在过量和情景差异是不同指标。缺少成本、重量、类别或实际记录时显示不可用；已记录的零显示为零。','Pembaziran sebenar, lebihan berpotensi dan perbezaan senario ialah ukuran berbeza. Kos, berat, kategori atau hasil yang tiada kekal tidak tersedia; sifar direkod ditunjukkan sebagai sifar.')}</p><p>{c('Planning can support SDG 12.3 by reducing avoidable retail food waste. CO₂e estimates describe possible impacts and do not prove achieved emissions reductions.','规划可通过减少零售端可避免的食品浪费支持 SDG 12.3。CO₂e 是可能影响的估算，不证明已实现减排。','Perancangan boleh menyokong SDG 12.3 dengan mengurangkan pembaziran runcit yang boleh dielak. Anggaran CO₂e tidak membuktikan pengurangan pelepasan sebenar.')}</p></section>
    <div className="cp3-actions"><button type="button" className="btn btn--primary" onClick={onBack}>{c('Back to purchase plan','返回采购计划','Kembali ke pelan belian')}</button>{onNew&&<button type="button" className="btn btn--ghost" onClick={onNew}>{c('Start a new plan','开始新计划','Mulakan pelan baharu')}</button>}</div>
  </main>;
}
