import { translateForLanguage, type Language } from "../i18n/index.ts";
import type { AnalysisReport } from "../engine.ts";

export type ReportLanguageChoice = Language | "follow";
export const reportLocale = (language: Language): string => language === "zh" ? "zh-CN" : language === "ms" ? "ms-MY" : "en-GB";

/** Source-provided labels and names are evidence, not interface copy. */
export function protectedReportValues(report: AnalysisReport): ReadonlySet<string> {
  const values = new Set([report.metadata.shopName, report.metadata.datasetName, report.metadata.sourceName, report.metadata.datasetId, report.metadata.sourceSha256].filter(value => value !== "Not supplied"));
  const sourceColumns = new Set(["Product name", "Product code", "Pack size", "Product key", "Supplier", "Supplier ID", "Source column", "Observed value", "Source rows", "Source names", "Source values", "Source boundary", "Factor label", "Description"]);
  for (const table of report.tables) table.columns.forEach((label, index) => {
    if (sourceColumns.has(label)) for (const row of table.rows) {
      if (table.id === "scenarios" && label === "Supplier" && row[table.columns.indexOf("Supplier ID")] === "current-terms") continue;
      if (typeof row[index] === "string" && row[index] !== "Not supplied") values.add(row[index]);
    }
  });
  return values;
}

// The report contract stays in English so column lookups and calculations remain stable.
// These are presentation strings used by PDF, print and workbook exports.
const copy: Record<string, readonly [string, string]> = {
  "RETAILER FILE ANALYSIS": ["零售商数据分析", "ANALISIS FAIL PERUNCIT"],
  "RETAILER ANALYSIS": ["零售商分析", "ANALISIS PERUNCIT"],
  "ANALYSIS REPORT": ["分析报告", "LAPORAN ANALISIS"],
  "StockLess retailer analysis": ["StockLess 零售商分析", "Analisis peruncit StockLess"],
  "A clearer view of your": ["更清楚地了解您的", "Gambaran lebih jelas tentang"],
  "next purchase decision.": ["下一次采购决策。", "keputusan belian seterusnya."],
  "A clearer view of your next purchase decision": ["更清楚地了解您的下一次采购决策", "Gambaran lebih jelas tentang keputusan belian seterusnya"],
  "A practical check before placing the next order": ["下次下单前的实用核查", "Semakan praktikal sebelum pesanan seterusnya"],
  "SHOP": ["店铺", "KEDAI"], "DATASET": ["数据集", "SET DATA"],
  "RECORDED PERIOD": ["记录期间", "TEMPOH DIREKOD"], "SOURCE FILE": ["来源文件", "FAIL SUMBER"],
  "ANALYSIS DATE": ["分析日期", "TARIKH ANALISIS"],
  "PLANNED PURCHASE SPEND": ["计划采购金额", "PERBELANJAAN BELIAN DIRANCANG"],
  "POTENTIAL EXCESS COST": ["潜在过量库存成本", "KOS LEBIHAN BERPOTENSI"],
  "POTENTIAL EXCESS CO2E": ["潜在过量库存 CO₂e", "CO₂e LEBIHAN BERPOTENSI"],
  "PLANNED ORDER LINES": ["计划订单项", "BARIS PESANAN DIRANCANG"],
  "PRODUCTS IN REPORT": ["报告中的商品", "PRODUK DALAM LAPORAN"],
  "COMPLETE SALES HISTORIES": ["完整销售记录", "SEJARAH JUALAN LENGKAP"],
  "ORDERS TO REVIEW": ["待复核订单", "PESANAN UNTUK DISEMAK"],
  "Current plan · partial total": ["当前计划 · 部分合计", "Pelan semasa · jumlah separa"],
  "Estimated · partial total": ["估算 · 部分合计", "Anggaran · jumlah separa"],
  "Estimated · partial coverage": ["估算 · 部分覆盖", "Anggaran · liputan separa"],
  "Positive quantities only": ["仅含正数订购量", "Kuantiti positif sahaja"],
  "Check these planned orders before placing them": ["下单前检查这些计划订单", "Semak pesanan dirancang sebelum membuat pesanan"],
  "No orders flagged by the current purchase check.": ["当前采购检查未标出需要复核的订单。", "Tiada pesanan ditandakan oleh semakan belian semasa."],
  "Read the numbers with context": ["结合背景理解数字", "Baca angka mengikut konteks"],
  "Forecasts, money and CO2e are estimates. Recorded outcomes are separate. Missing values and unentered quantities are not zero.": ["预测、金额和 CO₂e 均为估算；已记录结果单独列示。缺失值及未输入数量不等于零。", "Ramalan, wang dan CO₂e ialah anggaran; hasil direkod secara berasingan. Nilai yang tiada dan kuantiti belum diisi bukan sifar."],
  "Your purchase plan": ["您的采购计划", "Pelan belian anda"],
  "Current positive planned quantities, grouped for a quick order check.": ["按当前正数计划订购量汇总，便于快速核查。", "Kuantiti positif dalam pelan semasa, dikumpulkan untuk semakan cepat."],
  "Review flagged orders first": ["先复核已标记的订单", "Semak pesanan bertanda dahulu"],
  "Why these orders were flagged": ["这些订单被标记的原因", "Mengapa pesanan ini ditandakan"],
  "Purchase explanations for the current overstock-risk orders.": ["当前有过量库存风险的订单说明。", "Penjelasan bagi pesanan semasa yang berisiko lebihan stok."],
  "Recent sales pattern": ["近期销售趋势", "Corak jualan terkini"],
  "Recorded positive sales by week for the first 12 products; returns remain separate.": ["展示前 12 件商品每周记录的正向销量；退货另行计算。", "Jualan positif mingguan bagi 12 produk pertama; pulangan diasingkan."],
  "How to read these charts": ["如何阅读图表", "Cara membaca carta ini"],
  "Bars use a separate scale for each product; compare printed values across products. Dash = unavailable, 0 = recorded zero, shade = latest week.": ["每件商品的柱形图采用独立刻度；跨商品比较请看标注数值。横线＝无数据，0＝记录为零，浅色背景＝最近一周。", "Setiap produk menggunakan skala berasingan; bandingkan nilai bercetak antara produk. Sengkang = tiada data, 0 = sifar direkod, latar berwarna = minggu terkini."],
  "No weekly history": ["没有每周记录", "Tiada sejarah mingguan"],
  "No recent weekly sales values are available in this report.": ["本报告没有近期每周销量数据。", "Tiada nilai jualan mingguan terkini dalam laporan ini."],
  "Demand and stock": ["需求与库存", "Permintaan dan stok"],
  "Four-week demand ranges beside the stock and order figures used in the purchase check.": ["并列展示四周需求区间及采购检查使用的库存和订单数字。", "Julat permintaan empat minggu bersama angka stok dan pesanan yang digunakan dalam semakan belian."],
  "Estimate, not a guaranteed sale": ["估算值，并非保证销量", "Anggaran, bukan jualan terjamin"],
  "Demand ranges come from recorded history. Ready, Limited and Cannot assess describe data readiness, not purchase outcomes.": ["需求区间来自已记录的历史数据。“可评估”“有限”和“无法评估”描述数据就绪程度，并非采购结果。", "Julat permintaan berdasarkan sejarah direkod. Sedia, Terhad dan Tidak boleh dinilai menerangkan kesediaan data, bukan hasil belian."],
  "Why each order was checked": ["各订单的检查依据", "Sebab setiap pesanan disemak"],
  "Restock and expiry details remain separate from the headline demand view.": ["补货与保质期细节单独列示，不与主要需求概览混合。", "Butiran tambah stok dan luput diasingkan daripada ringkasan permintaan utama."],
  "Financial impact": ["财务影响", "Kesan kewangan"],
  "Estimated purchase commitment and possible excess-stock cost.": ["估算采购承诺金额及可能的过量库存成本。", "Anggaran komitmen belian dan kos lebihan stok yang mungkin."],
  "PLANNED SPEND": ["计划支出", "BELANJA DIRANCANG"],
  "EXCESS-STOCK COST": ["过量库存成本", "KOS LEBIHAN STOK"],
  "COMPARABLE PLAN": ["可比计划", "PELAN SETARA"],
  "RESTOCK SCENARIO": ["补货情景", "SENARIO TAMBAH STOK"],
  "Current positive orders": ["当前正数订单", "Pesanan positif semasa"],
  "Comparable products only": ["仅可比商品", "Produk setara sahaja"],
  "Estimated scenario": ["估算情景", "Senario anggaran"],
  "Partial totals": ["部分合计", "Jumlah separa"],
  "Potential carbon impact": ["潜在碳排放影响", "Kesan karbon berpotensi"],
  "CO2e is a partial estimate and is not a measured reduction.": ["CO₂e 为部分估算，并非已测得的减排量。", "CO₂e ialah anggaran separa, bukan pengurangan yang diukur."],
  "LOWER ESTIMATE": ["估算下限", "ANGGARAN RENDAH"],
  "UPPER ESTIMATE": ["估算上限", "ANGGARAN TINGGI"],
  "PRODUCT COVERAGE": ["商品覆盖率", "LIPUTAN PRODUK"],
  "Scenario range": ["情景区间", "Julat senario"],
  "Included / all products": ["纳入／全部商品", "Termasuk / semua produk"],
  "Interpretation": ["结果解释", "Tafsiran"],
  "Estimated CO2e is separate from recorded waste and achieved reductions. Unavailable product values are not zero.": ["估算 CO₂e 与已记录浪费及已实现减排分开列示。不可用的商品数值不等于零。", "Anggaran CO₂e diasingkan daripada sisa direkod dan pengurangan tercapai. Nilai produk yang tiada bukan sifar."],
  "Evidence behind included estimates": ["纳入估算的依据", "Bukti di sebalik anggaran yang disertakan"],
  "Factor labels and source names for potential-excess estimates.": ["潜在过量库存估算所用的系数标签与来源名称。", "Label faktor dan nama sumber bagi anggaran lebihan berpotensi."],
  "Recorded outcomes and data issues": ["已记录结果与数据问题", "Hasil direkod dan isu data"],
  "Actual records are kept distinct from forecast and planning estimates.": ["实际记录与预测及计划估算分开列示。", "Rekod sebenar diasingkan daripada ramalan dan anggaran perancangan."],
  "Problems to fix": ["待修正问题", "Masalah untuk dibetulkan"],
  "Review source rows and missing costs before relying on affected estimates.": ["使用受影响的估算值前，请检查来源行和缺失的成本。", "Semak baris sumber dan kos yang tiada sebelum bergantung pada anggaran terjejas."],
  "No supplier price is assumed": ["不假定供应商价格", "Harga pembekal tidak diandaikan"],
  "Supplier scenario rows, when present, describe quantities and timing. They do not establish achieved savings.": ["供应商情景仅描述数量与时间，并不代表已实现节省。", "Baris senario pembekal menerangkan kuantiti dan masa, bukan penjimatan yang telah dicapai."],
  "How to use this report": ["如何使用本报告", "Cara menggunakan laporan ini"],
  "Definitions, limits and source information for an informed purchase decision.": ["定义、限制和来源信息，帮助您作出采购决定。", "Takrif, had dan maklumat sumber untuk keputusan belian yang bermaklumat."],
  "Where the full evidence lives": ["完整依据在哪里", "Lokasi bukti lengkap"],
  "This visual report highlights current decisions. The unchanged analysis workbook contains complete sales rows, weekly history and per-product evidence.": ["本视觉报告突出当前决策；分析 Excel 包含完整销售行、每周历史和商品级依据。", "Laporan visual ini menonjolkan keputusan semasa. Buku kerja analisis mengandungi semua baris jualan, sejarah mingguan dan bukti bagi setiap produk."],
  "No records available": ["没有可用记录", "Tiada rekod tersedia"],
  "There are no rows for this section in the current report.": ["当前报告的这一部分没有数据行。", "Tiada baris bagi bahagian ini dalam laporan semasa."],
  "Product": ["商品", "Produk"], "PRODUCT": ["商品", "PRODUK"],
  "PLANNED QUANTITY": ["计划数量", "KUANTITI DIRANCANG"],
  "PURCHASE CHECK": ["采购检查", "SEMAKAN BELIAN"], "REASON TO REVIEW": ["复核原因", "SEBAB SEMAKAN"],
  "PRODUCT · READINESS": ["商品 · 就绪程度", "PRODUK · KESEDIAAN"],
  "4-WEEK DEMAND": ["四周需求", "PERMINTAAN 4 MINGGU"], "IN STOCK": ["现有库存", "STOK SEMASA"],
  "INCOMING": ["在途", "AKAN TIBA"], "PLANNED": ["计划量", "DIRANCANG"],
  "RESTOCK": ["补货", "TAMBAH STOK"], "BEFORE EXPIRY": ["到期前", "SEBELUM LUPUT"],
  "AFTER EXPIRY": ["到期后", "SELEPAS LUPUT"], "SHELF-LIFE CAP": ["保质期上限", "HAD JANGKA HAYAT"],
  "EXPLANATION / LIMIT": ["说明／限制", "PENJELASAN / HAD"],
  "PLAN SPEND": ["计划支出", "BELANJA PELAN"], "COMMITMENT": ["采购承诺", "KOMITMEN"],
  "EXCESS COST": ["过量成本", "KOS LEBIHAN"], "SCENARIO": ["情景", "SENARIO"],
  "DIFFERENCE": ["差额", "PERBEZAAN"], "LIMITATION": ["限制", "HAD"],
  "RECORDED WASTE": ["已记录浪费", "SISA DIREKOD"],
  "POTENTIAL EXCESS": ["潜在过量", "LEBIHAN BERPOTENSI"],
  "SCENARIO DIFFERENCE": ["情景差异", "PERBEZAAN SENARIO"],
  "MASS (KG)": ["质量 (KG)", "JISIM (KG)"], "CO2E (KG)": ["CO₂e (KG)", "CO₂e (KG)"],
  "FACTOR": ["系数", "FAKTOR"], "SOURCE NAMES": ["来源名称", "NAMA SUMBER"],
  "KIND": ["类型", "JENIS"], "DATE": ["日期", "TARIKH"],
  "QUANTITY": ["数量", "KUANTITI"], "CONVERSION SOURCE": ["换算来源", "SUMBER PENUKARAN"],
  "SOURCE ROW": ["来源行", "BARIS SUMBER"], "ISSUE": ["问题", "ISU"],
  "REASON": ["原因", "SEBAB"], "CORRECTIVE ACTION": ["修正措施", "TINDAKAN PEMBETULAN"],
  "PROVENANCE": ["来源信息", "ASAL USUL"], "VALUE": ["值", "NILAI"],
  "SOURCE": ["来源", "SUMBER"], "FILE": ["文件", "FAIL"],
  "DATASET ID": ["数据集 ID", "ID SET DATA"], "GENERATED": ["生成时间", "DIJANA"],
  "SOURCE SHA-256": ["来源 SHA-256", "SHA-256 SUMBER"],
  "Field": ["字段", "Medan"], "Value": ["值", "Nilai"],
  "Shop": ["店铺", "Kedai"], "Dataset": ["数据集", "Set data"],
  "Data source": ["数据来源", "Sumber data"], "Source file": ["来源文件", "Fail sumber"],
  "Worksheet": ["工作表", "Helaian kerja"], "Analysis date": ["分析日期", "Tarikh analisis"],
  "Reporting period start": ["报告期间起始", "Mula tempoh laporan"],
  "Reporting period end": ["报告期间结束", "Tamat tempoh laporan"],
  "Generated at": ["生成时间", "Dijana pada"],
  "Snapshot ID": ["快照 ID", "ID syot kilat"],
  "Forecast policy": ["预测规则", "Dasar ramalan"],
  "Currency": ["货币", "Mata wang"],
  "Rows in": ["输入行数", "Baris masuk"], "Rows used": ["使用行数", "Baris digunakan"],
  "Rows left out": ["排除行数", "Baris dikecualikan"],
  "Product name": ["商品名称", "Nama produk"],
  "Product code": ["商品编码", "Kod produk"],
  "Pack size": ["包装规格", "Saiz pek"],
  "Product key": ["商品键", "Kunci produk"],
  "Readiness": ["数据就绪程度", "Kesediaan data"],
  "Reason": ["原因", "Sebab"],
  "Recorded weeks in last 8": ["最近八周有记录周数", "Minggu direkod dalam 8 minggu terakhir"],
  "Demand pattern": ["需求模式", "Corak permintaan"],
  "Demand low (4 weeks)": ["四周需求下限", "Permintaan rendah (4 minggu)"],
  "Demand high (4 weeks)": ["四周需求上限", "Permintaan tinggi (4 minggu)"],
  "Central demand (unrounded)": ["需求中值（未取整）", "Permintaan tengah (belum dibundar)"],
  "Current stock": ["当前库存", "Stok semasa"],
  "Stock count date": ["盘点日期", "Tarikh kiraan stok"],
  "Incoming quantity": ["在途数量", "Kuantiti akan tiba"],
  "Planned quantity": ["计划数量", "Kuantiti dirancang"],
  "Purchase check": ["采购检查", "Semakan belian"],
  "Purchase explanation": ["采购说明", "Penjelasan belian"],
  "Restock recommendation": ["补货建议", "Cadangan tambah stok"],
  "Before expiry adjustment": ["到期前调整", "Pelarasan sebelum luput"],
  "After expiry adjustment": ["到期后调整", "Pelarasan selepas luput"],
  "Restock limitation": ["补货限制", "Had tambah stok"],
  "Shelf-life cap": ["保质期上限", "Had jangka hayat"],
  "Planned spend (MYR)": ["计划支出 (MYR)", "Belanja dirancang (MYR)"],
  "Excess-stock cost (MYR)": ["过量库存成本 (MYR)", "Kos lebihan stok (MYR)"],
  "Cost limitation": ["成本限制", "Had kos"],
  "Source": ["来源", "Sumber"],
  "Source row": ["来源行", "Baris sumber"],
  "Date": ["日期", "Tarikh"],
  "Recorded quantity": ["记录数量", "Kuantiti direkod"],
  "Positive sales": ["正向销量", "Jualan positif"],
  "Returns": ["退货", "Pulangan"],
  "Use state": ["使用状态", "Status penggunaan"],
  "Issue IDs": ["问题 ID", "ID isu"],
  "Week start": ["周开始日期", "Mula minggu"],
  "Week end": ["周结束日期", "Tamat minggu"],
  "Net quantity": ["净数量", "Kuantiti bersih"],
  "Week state": ["该周状态", "Status minggu"],
  "Record count": ["记录数", "Bilangan rekod"],
  "Source rows": ["来源行", "Baris sumber"],
  "Supplier": ["供应商", "Pembekal"],
  "Supplier ID": ["供应商 ID", "ID pembekal"],
  "Case size": ["箱规", "Saiz kotak"],
  "Minimum order": ["最低订购量", "Pesanan minimum"],
  "Lead time (days)": ["交货时间（天）", "Tempoh penghantaran (hari)"],
  "Scenario quantity": ["情景数量", "Kuantiti senario"],
  "Cases": ["箱数", "Bilangan kotak"],
  "Arrival date": ["到货日期", "Tarikh ketibaan"],
  "Beyond 4 weeks": ["超过四周", "Melebihi 4 minggu"],
  "Extra units": ["额外单位数", "Unit tambahan"],
  "Status": ["状态", "Status"],
  "Potential excess units": ["潜在过量单位数", "Unit lebihan berpotensi"],
  "Potential shortfall units": ["潜在缺货单位数", "Unit kekurangan berpotensi"],
  "Incoming spend (MYR)": ["在途支出 (MYR)", "Belanja stok akan tiba (MYR)"],
  "Combined commitment (MYR)": ["合计采购承诺 (MYR)", "Jumlah komitmen (MYR)"],
  "Scenario spend (MYR)": ["情景支出 (MYR)", "Belanja senario (MYR)"],
  "Estimated purchase-spend difference (MYR)": ["估算采购支出差额 (MYR)", "Anggaran perbezaan belanja belian (MYR)"],
  "Exclusion or limitation": ["排除或限制原因", "Pengecualian atau had"],
  "Measure": ["指标", "Ukuran"],
  "State": ["状态", "Keadaan"],
  "Estimated amount (MYR)": ["估算金额 (MYR)", "Amaun anggaran (MYR)"],
  "Included products": ["纳入商品数", "Produk disertakan"],
  "Excluded products": ["排除商品数", "Produk dikecualikan"],
  "Limitation": ["限制", "Had"],
  "Category": ["类别", "Kategori"],
  "Quantity": ["数量", "Kuantiti"],
  "Unit": ["单位", "Unit"],
  "Mass basis": ["质量依据", "Asas jisim"],
  "CO2e low (kg)": ["CO₂e 下限 (kg)", "CO₂e rendah (kg)"],
  "CO2e high (kg)": ["CO₂e 上限 (kg)", "CO₂e tinggi (kg)"],
  "Factor (kg CO2e/kg)": ["系数 (kg CO₂e/kg)", "Faktor (kg CO₂e/kg)"],
  "Factor label": ["系数标签", "Label faktor"],
  "Source names": ["来源名称", "Nama sumber"],
  "Source values": ["来源数值", "Nilai sumber"],
  "Source boundary": ["来源边界", "Sempadan sumber"],
  "Conversion source": ["换算来源", "Sumber penukaran"],
  "Calculation": ["计算方式", "Pengiraan"],
  "Baseline": ["基准", "Garis dasar"],
  "Estimated CO2e (kg)": ["估算 CO₂e (kg)", "Anggaran CO₂e (kg)"],
  "Mass from sources-agree factors (kg)": ["来源一致系数的质量 (kg)", "Jisim daripada faktor sumber sepadan (kg)"],
  "Mass from estimated factors (kg)": ["估算系数的质量 (kg)", "Jisim daripada faktor anggaran (kg)"],
  "Record ID": ["记录 ID", "ID rekod"],
  "Kind": ["类型", "Jenis"],
  "kg per unit": ["每单位千克数", "kg seunit"],
  "Description": ["描述", "Penerangan"],
  "Recorded at": ["记录时间", "Direkod pada"],
  "Updated at": ["更新时间", "Dikemas kini pada"],
  "Issue": ["问题", "Isu"],
  "Source column": ["来源列", "Lajur sumber"],
  "Observed value": ["观察值", "Nilai diperhatikan"],
  "Corrective action": ["修正措施", "Tindakan pembetulan"],
  "Resolution state": ["解决状态", "Status penyelesaian"],
  "Quantity unit": ["数量单位", "Unit kuantiti"],
  "Quantity source": ["数量来源", "Sumber kuantiti"],
  "Export date": ["导出日期", "Tarikh eksport"],
  "Explanation": ["说明", "Penjelasan"],
  "Overview": ["概览", "Gambaran keseluruhan"],
  "Weekly sales": ["每周销量", "Jualan mingguan"],
  "Order summary": ["订单概览", "Ringkasan pesanan"],
  "Weekly sales history": ["每周销售记录", "Sejarah jualan mingguan"],
  "Last eight complete weeks": ["最近八个完整周", "Lapan minggu lengkap terakhir"],
  "Coverage": ["覆盖率", "Liputan"], "Weeks": ["周数", "Minggu"],
  "Sales status": ["销售状态", "Status jualan"], "SKU": ["SKU", "SKU"], "Pack": ["包装", "Pek"],
  "What needs attention": ["需要关注的事项", "Perkara yang perlu diberi perhatian"],
  "Current purchase orders": ["当前采购订单", "Pesanan belian semasa"],
  "Entered supplier terms": ["已填写的供应商条件", "Terma pembekal dimasukkan"],
  "The Purchase Orders sheet contains the complete order list. Quantities are current plan entries; this export does not place an order.": ["“采购订单”工作表包含完整订单清单。数量来自当前计划；导出不会实际下单。", "Helaian Pesanan Belian mengandungi senarai lengkap. Kuantiti berasal daripada pelan semasa; eksport ini tidak membuat pesanan."],
  "Missing weeks are not treated as zero. Complete source history remains in Weekly Demand History.": ["缺失的周不计为零。完整来源历史记录见“每周需求记录”。", "Minggu yang tiada tidak dikira sifar. Sejarah sumber lengkap kekal dalam Sejarah Permintaan Mingguan."],
  "Dash = unavailable week. 0 = recorded zero sales. Full history is on the Weekly sales sheet.": ["横线＝该周无数据；0＝销量记录为零。完整记录见“每周销量”工作表。", "Sengkang = minggu tanpa data; 0 = jualan sifar direkod. Sejarah lengkap ada pada helaian Jualan mingguan."],
  "No weekly sales history is available for this report.": ["本报告没有每周销售记录。", "Tiada sejarah jualan mingguan untuk laporan ini."],
  "Forecasts and CO₂e are estimates. Missing values are not treated as zero.": ["预测和 CO₂e 均为估算。缺失值不计为零。", "Ramalan dan CO₂e ialah anggaran. Nilai yang tiada tidak dikira sifar."],
  "Teal = recorded value. Amber = missing week. A numeric 0 is a recorded zero.": ["青绿色＝已有记录；琥珀色＝该周缺失；数字 0 表示记录为零。", "Hijau kebiruan = nilai direkod. Jingga = minggu tiada data. Angka 0 ialah sifar yang direkod."],
  "No planned orders. Enter a positive quantity in Purchase plan.": ["没有计划订单。请在采购计划中输入正数订购量。", "Tiada pesanan dirancang. Masukkan kuantiti positif dalam Pelan belian."],
  "No outcome recorded.": ["没有已记录的结果。", "Tiada hasil direkod."],
  "No records available for this section.": ["本部分没有可用记录。", "Tiada rekod tersedia bagi bahagian ini."],
  "Use your browser's Print dialog and select “Save as PDF”. The detailed Excel workbook includes complete sales history and planning evidence.": ["在浏览器打印窗口中选择“保存为 PDF”。详细 Excel 文件包含完整销售记录和计划依据。", "Dalam dialog Cetak pelayar, pilih “Simpan sebagai PDF”. Buku kerja Excel terperinci mengandungi sejarah jualan dan bukti perancangan lengkap."],
  "No recent weekly sales values are available.": ["没有近期每周销量数据。", "Tiada nilai jualan mingguan terkini."],
  "Charts show the first 12 products. The Excel workbook contains complete weekly history.": ["图表展示前 12 件商品；Excel 文件包含完整每周记录。", "Carta menunjukkan 12 produk pertama; buku kerja Excel mengandungi sejarah mingguan lengkap."],
  "Recorded waste": ["已记录浪费", "Sisa direkod"],
  "Potential excess": ["潜在过量", "Lebihan berpotensi"],
  "Scenario difference": ["情景差异", "Perbezaan senario"],
  "Mass (kg)": ["质量 (kg)", "Jisim (kg)"],
  "CO2e (kg)": ["CO₂e (kg)", "CO₂e (kg)"],
  "Factor": ["系数", "Faktor"],
  "Explanations and limitations": ["说明与限制", "Penjelasan dan had"],
  "Source and provenance": ["来源与出处", "Sumber dan asal usul"],
  "Forecasts, purchase commitments, potential excess and CO2e are estimates; recorded sales and waste are reported separately.": ["预测、采购承诺、潜在过量库存及 CO₂e 均为估算；已记录销量和浪费另行报告。", "Ramalan, komitmen belian, lebihan berpotensi dan CO₂e ialah anggaran; jualan dan sisa direkod dilaporkan berasingan."],
  "Missing values and unentered quantities are not replaced by zero. Returns remain separate from positive sales demand.": ["缺失值和未输入数量不会用零代替。退货与正向销售需求分开计算。", "Nilai yang tiada dan kuantiti belum diisi tidak diganti dengan sifar. Pulangan diasingkan daripada permintaan jualan positif."],
  "The order list uses current Purchase plan quantities. Editing the plan changes the next export; it does not establish an actual purchase or stock outcome.": ["订单清单采用当前采购计划的数量。修改计划会改变下一次导出，但不代表实际采购或库存结果。", "Senarai pesanan menggunakan kuantiti Pelan belian semasa. Mengubah pelan mengubah eksport seterusnya; ia bukan bukti belian atau hasil stok sebenar."],
  "Supplier comparisons are quantities and arrival dates; no supplier price or achieved savings is assumed.": ["供应商比较仅涉及数量与到货日期，不假定供应商价格或已实现节省。", "Perbandingan pembekal meliputi kuantiti dan tarikh ketibaan; harga pembekal atau penjimatan tercapai tidak diandaikan."],
  "Current product and scenario results describe the analysis date and the next four-week demand horizon. The reporting period filters recorded outcomes, not the current forecast or order list.": ["当前商品和情景结果基于分析日期及未来四周需求。报告期间只筛选已记录结果，不筛选当前预测或订单清单。", "Hasil produk dan senario semasa merujuk tarikh analisis dan permintaan empat minggu berikutnya. Tempoh laporan menapis hasil direkod, bukan ramalan atau senarai pesanan semasa."],
  "Only positive current planned quantities appear in the order list. Zero orders and unentered quantities remain distinct in Product Results.": ["订单清单仅列出当前正数计划量。零订购量与未输入数量在“商品结果”中分别显示。", "Hanya kuantiti positif semasa muncul dalam senarai pesanan. Pesanan sifar dan kuantiti belum diisi kekal berbeza dalam Hasil Produk."],
  "CO2e source agreement is not ground-truth validation or evidence of achieved emissions reductions.": ["CO₂e 来源一致并不等于实测验证，也不能证明已实现减排。", "Persetujuan sumber CO₂e bukan pengesahan sebenar atau bukti pengurangan pelepasan tercapai."],
  "Automatic planned quantities are labelled worked out by StockLess. AI-assigned categories retain model and source provenance and are not manual confirmations.": ["自动计算的计划数量会标注为 StockLess 计算。AI 分配的类别保留模型和来源信息，并非人工确认。", "Kuantiti pelan automatik dilabel sebagai dikira oleh StockLess. Kategori yang ditetapkan AI mengekalkan maklumat model dan sumber, bukan pengesahan manual."],
  "Sample data: these results are illustrative and are not this retailer's recorded outcomes.": ["示例数据：这些结果仅供演示，并非该零售商的实际记录。", "Data sampel: hasil ini untuk ilustrasi dan bukan hasil direkod peruncit ini."],
  "Used": ["已使用", "Digunakan"], "Left out": ["未使用", "Dikecualikan"],
  "Ready": ["可评估", "Sedia"], "Limited": ["有限", "Terhad"],
  "Cannot assess": ["无法评估", "Tidak boleh dinilai"],
  "Not planned": ["未计划", "Belum dirancang"], "Cannot judge": ["无法判断", "Tidak boleh diputuskan"],
  "Not assessed": ["未评估", "Belum dinilai"],
  "Missing week": ["该周缺失", "Minggu tiada data"],
  "No waste record": ["没有浪费记录", "Tiada rekod sisa"],
  "Not supplied": ["未提供", "Tidak dibekalkan"],
  "Not applicable": ["不适用", "Tidak berkenaan"],
  "Not applied": ["未应用", "Tidak digunakan"],
  "Unconfirmed": ["未确认", "Belum disahkan"],
  "Unavailable": ["不可用", "Tidak tersedia"],
  "Not entered": ["未输入", "Belum diisi"],
  "Estimated": ["估算", "Anggaran"],
  "estimated": ["估算", "anggaran"],
  "recorded_waste": ["已记录浪费", "sisa direkod"],
  "potential_excess": ["潜在过量库存", "lebihan berpotensi"],
  "scenario_difference": ["情景差异", "perbezaan senario"],
  "no_record": ["无记录", "tiada rekod"],
  "not_entered": ["未输入", "belum diisi"],
  "unavailable": ["不可用", "tidak tersedia"],
  "available": ["可用", "tersedia"],
  "pieces": ["件", "unit"],
  "discarded": ["丢弃", "dibuang"],
  "expired": ["过期", "luput"],
  "Sample data": ["示例数据", "Data sampel"],
  "Retailer file": ["零售商文件", "Fail peruncit"],
  "No restock evidence.": ["没有补货依据。", "Tiada bukti tambah stok."],
  "No planned quantity entered.": ["未输入计划订购量。", "Tiada kuantiti dirancang diisi."],
  "Partial total: excluded products are not treated as zero.": ["部分合计：已排除商品不计为零。", "Jumlah separa: produk dikecualikan tidak dikira sifar."],
  "Estimated from seller unit costs.": ["根据卖方单位成本估算。", "Dianggarkan daripada kos unit penjual."],
  "Partial estimate: excluded products are not zero.": ["部分估算：已排除商品不计为零。", "Anggaran separa: produk dikecualikan bukan sifar."],
  "Estimate; separate from achieved environmental outcomes.": ["估算值；与已实现的环境结果分开列示。", "Anggaran; diasingkan daripada hasil alam sekitar yang dicapai."],
  "Product Results": ["商品结果", "Hasil Produk"],
  "Purchase Orders": ["采购订单", "Pesanan Belian"],
  "Sales Records": ["销售记录", "Rekod Jualan"],
  "Weekly Demand History": ["每周需求记录", "Sejarah Permintaan Mingguan"],
  "Supplier Scenarios": ["供应商情景", "Senario Pembekal"],
  "Financial Impact": ["财务影响", "Kesan Kewangan"],
  "Financial Totals": ["财务合计", "Jumlah Kewangan"],
  "CO2e Estimates": ["CO₂e 估算", "Anggaran CO₂e"],
  "CO2e Totals": ["CO₂e 合计", "Jumlah CO₂e"],
  "Recorded Outcomes": ["已记录结果", "Hasil Direkod"],
  "Problems to Fix": ["待修正问题", "Masalah untuk Dibetulkan"],
  "Explanations and Limits": ["说明与限制", "Penjelasan dan Had"],
  "Metadata": ["元数据", "Metadata"],
};

const templates: readonly [RegExp, (match: RegExpMatchArray, language: Language) => string][] = [
  [/^(\d+) ORDERS TO REVIEW$/, ([, count], language) => language === "zh" ? `${count} 项订单待复核` : `${count} PESANAN UNTUK DISEMAK`],
  [/^([\dA-Z]+) \/ RETAILER ANALYSIS$/, ([, section], language) => language === "zh" ? `${section} / 零售商分析` : `${section} / ANALISIS PERUNCIT`],
  [/^(\d+) planned order lines$/, ([, count], language) => language === "zh" ? `${count} 项计划订单` : `${count} baris pesanan dirancang`],
  [/^(\d+) of (\d+) planned order lines show overstock risk\. Check the highlighted rows\.$/, ([, risk, total], language) => language === "zh" ? `${total} 项计划订单中有 ${risk} 项存在过量库存风险。请检查高亮行。` : `${risk} daripada ${total} baris pesanan dirancang berisiko lebihan stok. Semak baris yang ditandakan.`],
  [/^(\d+) source issues also need review\. Forecasts are ranges; unentered values are not zero\.$/, ([, count], language) => language === "zh" ? `另有 ${count} 个来源数据问题需要复核。预测为区间；未输入的值不等于零。` : `${count} isu data sumber juga perlu disemak. Ramalan ialah julat; nilai belum diisi bukan sifar.`],
  [/^(\d+) planned order lines show overstock risk\. (\d+) source issues need review\. See Purchase Orders and Problems to Fix for details\.$/, ([, risk, problems], language) => language === "zh" ? `${risk} 项计划订单存在过量库存风险，${problems} 个来源数据问题需要复核。详情见“采购订单”和“待修正问题”。` : `${risk} baris pesanan dirancang berisiko lebihan stok; ${problems} isu sumber perlu disemak. Lihat Pesanan Belian dan Masalah untuk Dibetulkan.`],
  [/^PEAK (.+) · (\d+)\/(\d+) WEEKS RECORDED$/, ([, peak, count, total], language) => language === "zh" ? `峰值 ${peak} · 已记录 ${count}/${total} 周` : `PUNCAK ${peak} · ${count}/${total} MINGGU DIREKOD`],
  [/^Estimated purchase-spend difference: (.+)\. This is a scenario estimate, not achieved savings\.$/, ([, amount], language) => language === "zh" ? `估算采购支出差额：${amount}。这是情景估算，并非已实现节省。` : `Anggaran perbezaan belanja belian: ${amount}. Ini anggaran senario, bukan penjimatan yang telah dicapai.`],
  [/^Continued · products (\d+)-(\d+) of (\d+)\.$/, ([, start, end, total], language) => language === "zh" ? `续 · 第 ${start}–${end} 件商品，共 ${total} 件。` : `Sambungan · produk ${start}–${end} daripada ${total}.`],
  [/^(.+) · Analysis date (\d{4}-\d{2}-\d{2}) · Estimates where labelled$/, ([, shop, date], language) => language === "zh" ? `${shop} · 分析日期 ${date} · 标注处为估算` : `${shop} · Tarikh analisis ${date} · Anggaran jika dinyatakan`],
  [/^(\d+[\d,.]*) kg · Estimated$/, ([, amount], language) => language === "zh" ? `${amount} kg · 估算` : `${amount} kg · Anggaran`],
  [/^(.+) · Generated (.+)$/, ([, source, date], language) => language === "zh" ? `${reportText(source, language)} · 生成于 ${date}` : `${reportText(source, language)} · Dijana ${date}`],
  [/^Source SHA-256: (.+)$/, ([, value], language) => language === "zh" ? `来源 SHA-256：${value}` : `SHA-256 sumber: ${value}`],
  [/^(\d{4}-\d{2}-\d{2}) to (\d{4}-\d{2}-\d{2})$/, ([, from, to], language) => language === "zh" ? `${from} 至 ${to}` : `${from} hingga ${to}`],
];

export function reportText(value: string, language: Language): string {
  if (language === "en") return value;
  const normalized = value.replace(/\s+/g, " ").trim();
  const entry = copy[normalized];
  if (entry) return entry[language === "zh" ? 0 : 1];
  for (const [pattern, render] of templates) {
    const match = normalized.match(pattern);
    if (match) return render(match, language);
  }
  return translateForLanguage(value, language);
}

export function reportCell<T extends string | number>(value: T, language: Language): T {
  return (typeof value === "string" ? reportText(value, language) : value) as T;
}
